export { default as ReactSVG } from "./react.svg";
export { default as DeliveryMan } from "./DeliveryB-1.jpg";
export { default as DeliveryBike } from "./deliveryBike.jpg";
export { default as MegaBus } from "./megabus.png";
export { default as KFC } from "./kfc.png";
export { default as ChickenLicken } from "./chicken-licken.png";
export { default as KotaKhona } from "./kota-khona.png";
export { default as Galitos } from "./Galitos.png";
export { default as EmbaMall } from "./mall@Emba.jpeg";
